  # This is the security group for MYSQL and SSH
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  BuildsSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable communication SSH and MYSQL"
      VpcId: vpc-xxxxxxx
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        CidrIp: 0.0.0.0/0
      Tags: 
      - Key: Name 
        Value: SSH Security Group
      - Key: Owner 
        Value: sunilcricket64@gmail.com
